version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "18081:18081"
      - "18090:18090"
    environment:
      MONERODRPC_USER: "monerod_rpc"
      MONERODRPC_PASS: ""
      WALLETRPC_USER: "monerowallet_rpc"
      WALLETRPC_PASS: ""
